/**
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JobSubmission {
    'format'?: string;
    'source'?: string;
    'variableFlags'?: { [key: string]: string; };
    'variables'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "format",
            "baseName": "Format",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "Source",
            "type": "string",
            "format": ""
        },
        {
            "name": "variableFlags",
            "baseName": "VariableFlags",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "variables",
            "baseName": "Variables",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobSubmission.attributeTypeMap;
    }
    
    public constructor() {
    }
}

