/**
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobSubmission model module.
 * @module model/JobSubmission
 * @version 1.1.4
 */
class JobSubmission {
    /**
     * Constructs a new <code>JobSubmission</code>.
     * @alias module:model/JobSubmission
     */
    constructor() { 
        
        JobSubmission.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobSubmission</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobSubmission} obj Optional instance to populate.
     * @return {module:model/JobSubmission} The populated <code>JobSubmission</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobSubmission();

            if (data.hasOwnProperty('Format')) {
                obj['Format'] = ApiClient.convertToType(data['Format'], 'String');
            }
            if (data.hasOwnProperty('Source')) {
                obj['Source'] = ApiClient.convertToType(data['Source'], 'String');
            }
            if (data.hasOwnProperty('VariableFlags')) {
                obj['VariableFlags'] = ApiClient.convertToType(data['VariableFlags'], {'String': 'String'});
            }
            if (data.hasOwnProperty('Variables')) {
                obj['Variables'] = ApiClient.convertToType(data['Variables'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} Format
 */
JobSubmission.prototype['Format'] = undefined;

/**
 * @member {String} Source
 */
JobSubmission.prototype['Source'] = undefined;

/**
 * @member {Object.<String, String>} VariableFlags
 */
JobSubmission.prototype['VariableFlags'] = undefined;

/**
 * @member {String} Variables
 */
JobSubmission.prototype['Variables'] = undefined;






export default JobSubmission;

