/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobSubmission {
    #[serde(rename = "Format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "Source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "VariableFlags", skip_serializing_if = "Option::is_none")]
    pub variable_flags: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "Variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<String>,
}

impl JobSubmission {
    pub fn new() -> JobSubmission {
        JobSubmission {
            format: None,
            source: None,
            variable_flags: None,
            variables: None,
        }
    }
}


